#!/bin/bash
awk '/\/\/ Admin Actions/ {
print "const createFD = (amount: number) => {"
print "  if (!currentUser) return { success: false, message: '\''Please login'\'' };"
print "  if (amount < 1500) return { success: false, message: lang === '\''bn'\'' ? '\''সর্বনিম্ন ডিপোজিট ১৫০০ ৳'\'' : '\''Minimum deposit is 1500 ৳'\'' };"
print "  if (currentUser.balance < amount) return { success: false, message: lang === '\''bn'\'' ? '\''অপরিপ্রেক্ষিত ব্যালেন্স'\'' : '\''Insufficient balance'\'' };"
print "  "
print "  const now = Date.now();"
print "  const today = new Date().toISOString().slice(0, 10);"
print "  const maturityAt = now + 180 * 24 * 60 * 60 * 1000; // 6 months approx"
print "  const maturityDate = new Date(maturityAt).toISOString().slice(0, 10);"
print "  "
print "  const newFD: FixedDeposit = {"
print "    id: `fd_${Math.random().toString(36).substr(2, 9)}`,"
print "    principal: amount,"
print "    monthlyRate: 7.5,"
print "    startDate: today,"
print "    maturityDate: maturityDate,"
print "    activatedAt: now,"
print "    maturityAt: maturityAt,"
print "    lastClaimedAt: now,"
print "    totalClaimed: 0,"
print "    status: '\''active'\''"
print "  };"
print ""
print "  const newBalance = currentUser.balance - amount;"
print "  const updatedUser = {"
print "    ...currentUser,"
print "    balance: newBalance,"
print "    fds: [...(currentUser.fds || []), newFD]"
print "  };"
print "  "
print "  updateUserInState(updatedUser);"
print "  persistUserToFirestore(updatedUser);"
print ""
print "  const tx: Transaction = {"
print "    id: `tx_${Date.now()}`,"
print "    userId: currentUser.phone,"
print "    type: '\''fd_deposit'\'',"
print "    title: '\''FD Created'\'',"
print "    titleBn: '\''এফডি তৈরি'\'',"
print "    amount: -amount,"
print "    status: '\''completed'\'',"
print "    date: today,"
print "    timestamp: now,"
print "    details: `Fixed Deposit (ID: ${newFD.id})`"
print "  };"
print "  "
print "  setTransactions((prev) => [tx, ...prev]);"
print "  persistTxToFirestore(tx);"
print ""
print "  showToast(lang === '\''bn'\'' ? '\''ফিক্সড ডিপোজিট সফলভাবে তৈরি হয়েছে!'\'' : '\''Fixed Deposit created successfully!'\'', '\''success'\'');"
print "  return { success: true, message: '\''FD created'\'' };"
print "};"
print ""
print "const claimFDProfit = (fdId: string) => {"
print "  if (!currentUser) return { success: false, message: '\''Please login'\'' };"
print "  "
print "  const fdIndex = (currentUser.fds || []).findIndex(f => f.id === fdId);"
print "  if (fdIndex === -1) return { success: false, message: '\''FD not found'\'' };"
print "  "
print "  const fd = currentUser.fds![fdIndex];"
print "  if (fd.status !== '\''active'\'') return { success: false, message: '\''FD is not active'\'' };"
print "  "
print "  const now = Date.now();"
print "  const fiveDaysMs = 5 * 24 * 60 * 60 * 1000;"
print "  const elapsed = now - (fd.lastClaimedAt || fd.activatedAt);"
print "  "
print "  if (elapsed < fiveDaysMs) {"
print "    return { success: false, message: lang === '\''bn'\'' ? '\''এখনও ৫ দিন পূর্ণ হয়নি'\'' : '\''5 days have not passed yet'\'' };"
print "  }"
print "  "
print "  const cycles = Math.floor(elapsed / fiveDaysMs);"
print "  const profitPerCycle = (fd.principal * 7.5 / 100) / 6;"
print "  const totalProfit = profitPerCycle * cycles;"
print "  "
print "  const newLastClaimedAt = (fd.lastClaimedAt || fd.activatedAt) + (cycles * fiveDaysMs);"
print "  "
print "  const updatedFD = {"
print "    ...fd,"
print "    lastClaimedAt: newLastClaimedAt,"
print "    totalClaimed: fd.totalClaimed + totalProfit,"
print "    status: (now >= fd.maturityAt) ? '\''matured'\'' as const : '\''active'\'' as const"
print "  };"
print "  "
print "  const updatedFds = [...(currentUser.fds || [])];"
print "  updatedFds[fdIndex] = updatedFD;"
print "  "
print "  const updatedUser = {"
print "    ...currentUser,"
print "    balance: currentUser.balance + totalProfit,"
print "    fds: updatedFds"
print "  };"
print "  "
print "  updateUserInState(updatedUser);"
print "  persistUserToFirestore(updatedUser);"
print "  "
print "  const tx: Transaction = {"
print "    id: `tx_${Date.now()}`,"
print "    userId: currentUser.phone,"
print "    type: '\''fd_profit'\'',"
print "    title: '\''FD Profit Claimed'\'',"
print "    titleBn: '\''এফডি প্রফিট সংগ্রহ'\'',"
print "    amount: totalProfit,"
print "    status: '\''completed'\'',"
print "    date: new Date().toISOString().slice(0, 10),"
print "    timestamp: now,"
print "    details: `FD ID: ${fdId}`"
print "  };"
print "  "
print "  setTransactions((prev) => [tx, ...prev]);"
print "  persistTxToFirestore(tx);"
print "  "
print "  confetti({ particleCount: 50, spread: 60, origin: { y: 0.7 } });"
print "  showToast(lang === '\''bn'\'' ? `প্রফিট ৳${totalProfit.toFixed(2)} সংগ্রহ করা হয়েছে!` : `Profit ৳${totalProfit.toFixed(2)} claimed!`, '\''success'\'');"
print "  return { success: true, message: '\''Profit claimed'\'', amount: totalProfit };"
print "};"
print ""
print $0
next
}
{ print }' src/context/AppContext.tsx > src/context/AppContext.tsx.new && mv src/context/AppContext.tsx.new src/context/AppContext.tsx
